spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/HilalSolak/Config-Server
          force-pull: true
server:
  port: 8888


